### ISSUE TITLE
Sun and Moon icons don't render correctly in Safari. 

### ISSUE THREAD

**Issue by Gchism94** [codebucks27/Next.js-Developer-Portfolio-Starter-Code#3]
Greetings! Thanks for such a wonderful website template! 

I just debugged an issue with the sun and moon icons rendering much too large in Safari. I noticed that your demo site has this issue as well. 

If you're interested, here is the solution that worked for me (e.g., `MoonIcon`): 
```javascript
export const MoonIcon = ({ className, ...rest }) => (
  <div
    className={`w-6 h-6 ${className}`} // Change w-full h-auto to w-6 h-6 or desired size
    {...rest}
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
    >
      {/* Rest of the SVG code */}
    </svg>
  </div>
);
``` 

Thanks again!
-Greg

**Comment by codebucks27** [comment]
Hey Greg,

Thanks for pointing that out and the solution as well.
I'll try it out.

Thanks again.

Regards,
CodeBucks

**Comment by codebucks27** [comment]
Hey Greg,

Thanks for pointing that out and the solution as well.

Here the another solution that I have tried by adding the width and height in the `button` element.
Make sure you use this solution in the Navbar.js file.

```
<button
  onClick={() => setMode(mode === "light" ? "dark" : "light")}
  className={`w-6 h-6 ease ml-3 flex items-center justify-center rounded-full p-1
    ${mode === "light" ? "bg-dark  text-light" : "bg-light  text-dark"}
    `}
  aria-label="theme-switcher"
{mode === "light" ? (
    <SunIcon className={"fill-dark"} />
  ) : (
    <MoonIcon className={"fill-dark"} />
  )}
</button>
```

Thanks again.

Regards,
CodeBucks

**Comment by Gchism94** [comment]
Nice, thanks for letting me know in case I run into this again! This is a more elegant solution as well.

Glad I could help,
-Greg
