### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by manel00** [codebucks27/Next.js-Developer-Portfolio-Starter-Code#9]
```
$ npm run dev
 
> developer-portfolio-starter-code@0.1.0 dev /home/user/Documents/Next.js-Developer-Portfolio-Starter-Code
> next dev

/home/user/Documents/Next.js-Developer-Portfolio-Starter-Code/node_modules/next/dist/cli/next-dev.js:362
            showAll: args["--show-all"] ?? false,

SyntaxError: Unexpected token ?
```

Hello! I saw this problem, why is it not working?

Thank you

**Comment by codebucks27** [comment]
Hey,

I have checked the code again it is working. 
Make sure to install all the libraries using "npm install" before you start the server. 
I have tested this in Node.js 18.7.1 

let me know if you still face such problem.
